### ISSUE TITLE
Bug with the web app, when a discord username contain a non ISO-8859 char

### ISSUE THREAD

**Issue by bfiliatreault** [aibeira/swgoh-shard-bot-doc#5]
In the web app, after clicking on shard, and copy pasting a Discord Webhook Url, I got the following error
https://cdn.discordapp.com/attachments/477675271282098199/797887338033840178/unknown.png

The problem is my discord username contain a non ISO-8859 char.
For example: Filbe Lᴀᴍᴏɴ ⚜❄#9224

Workaround, remove any non ISO-8859 char from username.

For more information, search for the string "from: non iso" in discord.

You can also contact me on discord.

My new username is Filbe Lamon#9224

**Comment by aibeira** [comment]
This should be resolved.  Might require a forced-refresh / cache-bypass.
