### ISSUE TITLE
;arena Enhancement Request

### ISSUE THREAD

**Issue by wr8th3** [aibeira/swgoh-shard-bot-doc#7]
Command used: ;arena 11
Current output:
From 11, in 3 battles, you can reach is 1.
(11 → 7 → 3 → 1)

Desired output:
From 11, in 3 battles, you can reach is 1.
11(Player A) → 7(PlayerB) → 3(PlayerC) → 1(PlayerD)

The expectation is the data uses the current player rankings shown in ;prl output to determine which player is in the particular positions.

**Comment by aibeira** [comment]
I have made a change to display this, and sent a screenshot to the Discord support channel, and am just waiting to see if that is what @wr8th3 was thinking.

**Comment by aibeira** [comment]
This was rolled out on 2021-01-31.
